### ISSUE TITLE
No clue how to get the bot portion to start?

### ISSUE THREAD

**Issue by MrNewb** [RoqueDEV/fivemserverstatus#1]
could you add more detail on that to the readme? Only have the queue working myself

**Comment by draZer0** [comment]
Did you manage to start the bot? If yes, just add the enviroment variables in the setup.

**Comment by MrNewb** [comment]
I made one, discord bot seems to have started since im getting arguments passed but its not doing anything. =/ copied the channel ids in poped them in. im local hosting it atm to test but no luck

**Comment by draZer0** [comment]
did you change the server ip, token, channel ids etc in the config?

**Comment by draZer0** [comment]
i guess you fixed it since you dont respond anymore
