### ISSUE TITLE
Verandering

### ISSUE THREAD

**Issue by Nilsfctwente** [RoqueDEV/fivemserverstatus#10]
Hoi ik zag dat je nederlands bent daarom doe ik het ook nederlands

Ik probeer eigenlijk het zo te krijgen dat de status van de bot het aantal spelers is.
zou je mij hierbij willen helpen 

Alvast bedankt

PS: contact me op discord.gg/FhTXZQ

**Comment by draZer0** [comment]
Go to https://discord.js.org/#/docs/main/stable/general/welcome they probably have what you are looking for
