### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by mxnmsky** [RoqueDEV/fivemserverstatus#18]
![image](https://user-images.githubusercontent.com/63572886/79333848-6072a180-7f5e-11ea-9e19-02a708ab31cc.png)

i keep getting this error. Why?? do the channels have to be in id?

**Comment by RoqueDEV** [comment]
Yes, the channels have to be a id.  https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
