### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by WiKiPTYtb** [RoqueDEV/fivemserverstatus#19]
when I put +status and +statis clear it stop my bot

print:https://imgur.com/gBEbe81

**Comment by RoqueDEV** [comment]
Make sure to have the Administrator permission. If it does crash again reopen pls.

**Comment by WiKiPTYtb** [comment]
one thing please how i add other commands ?

**Comment by WiKiPTYtb** [comment]
if u can enter in contact with me via discord add me please: WiKiPTYtb#2541
