### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by fsocietystudios** [RoqueDEV/fivemserverstatus#2]
I put the right stuff into the URL_SERVER in the config.json , i woke up with this error. I didn't change anything , The bot was worked.

**Comment by draZer0** [comment]
can you send me your config.json?

**Comment by fsocietystudios** [comment]
Yes , here it is :
https://pastebin.com/BvpUCDP0

**Comment by draZer0** [comment]
i don't see anything wrong, did you manage to fix it already?

**Comment by fsocietystudios** [comment]
no

**Comment by RoqueDEV** [comment]
Hey LiorKoren14,

Did you already fix it? If not what error do you get?

**Comment by RoqueDEV** [comment]
No response closed.
