### ISSUE TITLE
i dont get how this works

### ISSUE THREAD

**Issue by julianpoelmann** [RoqueDEV/fivemserverstatus#22]
![afbeelding](https://user-images.githubusercontent.com/28513665/82837089-639b6e80-9ec8-11ea-8808-6cdde81d6687.png)
im doing my best but i never really used java and from what i understand you need to run that setup file buit i cant. im just trying to make the bot work for my server but i dont even understand the setup things

**Comment by MeshX4** [comment]
same here I have tried all sort of things still not being able to set the message to show server status

**Comment by RoqueDEV** [comment]
Read wiki
