### ISSUE TITLE
DiscordBot no longer installs

### ISSUE THREAD

**Issue by Neddings** [RoqueDEV/fivemserverstatus#3]
When trying to run npm i it comes up with errors referring to peerDependencies

Could someone please check why this is happening and also fix the package.json so the peerDependencies are handeled correctly

**Comment by draZer0** [comment]
Hello, can u send me the full error?

**Comment by draZer0** [comment]
Closed -> no response

**Comment by Neddings** [comment]
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.

**Comment by Neddings** [comment]
That's the exact error I keep getting when using the npm install to get the requirements

**Comment by RoqueDEV** [comment]
Hey Neddings,

What node.js version are you using? You can check that by doing `node -v`

Make sure you use **v10.16.3**.

**Comment by Neddings** [comment]
C:\Users\Neddings>node -v
**v10.16.3**

That's the correct version, the only problem lays in the fact that NPM has changed and with that, additional dependencies are no longer being installed. 

> The automatic install of peer dependencies was explicitly removed with npm 3, as it cause more problems than it tried to solve. You can read about it here for example:
> 
>     https://blog.npmjs.org/post/110924823920/npm-weekly-5
>     https://github.com/npm/npm/releases/tag/v3.0.0
> 
> So no, for the reasons given, you cannot install them automatically with npm 3 upwards.
>

**Comment by RoqueDEV** [comment]
Could you try reinstall NodeJS for me?

**Comment by Neddings** [comment]
npm WARN deprecated uws@100.0.1: New code is available at github.com/uNetworking/uWebSockets.js
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN fetch-timeout@0.0.2 requires a peer of node-fetch@^1.6.3 but none is installed. You must install peer dependencies yourself.

added 18 packages from 20 contributors and audited 20 packages in 2.645s
found 0 vulnerabilities

**Comment by RoqueDEV** [comment]
Could you try `npm i` and then `npm start`

**Comment by Neddings** [comment]
That is the output of  `npm i`

> npm WARN deprecated uws@100.0.1: New code is available at github.com/uNetworking/uWebSockets.js
> npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
> npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
> npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
> npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
> npm WARN fetch-timeout@0.0.2 requires a peer of node-fetch@^1.6.3 but none is installed. You must install peer dependencies yourself.
> 
> added 18 packages from 20 contributors and audited 20 packages in 2.645s
> found 0 vulnerabilities

The problem lies in the fact that NPM no longer does peer dependencies and those need to be declared in the file specifically in order for them to work.

**Comment by Nilsfctwente** [comment]
do you have do npm install discord.js?

**Comment by RoqueDEV** [comment]
Closed -> dunno why it doesn't work.

**Comment by Neddings** [comment]
After investigating the problems it seems it's fixed itself by just adding in some of the older NodeJS references. 

Thanks for taking the time to fix this.
