### ISSUE TITLE
server appears offline

### ISSUE THREAD

**Issue by TheHans58** [RoqueDEV/fivemserverstatus#30]
The server seems offline there is no problem with the ip address or the server. Can anyone help?
![71783222-8e4d5f00-2fdb-11ea-9c9e-0248aad100c4](https://user-images.githubusercontent.com/68406822/93141371-b81f5f80-f6ec-11ea-9d6b-2831a6e81dd8.png)

**Comment by AlexFernando001** [comment]
Make sure fivemqueue is running and setup correctly (try changing the resource name to its original if you renamed it)

**Comment by TheHans58** [comment]
Fivem queue works, I reinstalled the bot, no change still does not seem online.

When I request information from a different bot, it can receive data from the
 ip address without any problem.
![ddddd](https://user-images.githubusercontent.com/68406822/93219568-2b1fe900-f774-11ea-8975-1b03ffedf0cf.png)
![Adsız dpng](https://user-images.githubusercontent.com/68406822/93219791-67534980-f774-11ea-80b4-9d11feace975.png)

**Comment by TheHans58** [comment]
The problem was solved when the bot set up the same server with my fivem server. Thanks.
![Adsdsdız](https://user-images.githubusercontent.com/68406822/93223346-a388a900-f778-11ea-899c-e5922209ab56.png)
