### ISSUE TITLE
Error when starting the bot

### ISSUE THREAD

**Issue by Kevintherocket** [RoqueDEV/fivemserverstatus#4]
C:\Users\Administrator\Desktop\fivemserverstatus-master\fivemserverstatus-master
\Discord Bot>npm start

> FiveM-Server-Status-bot@1.0.0 start C:\Users\Administrator\Desktop\fivemserver
status-master\fivemserverstatus-master\Discord Bot
> node ./index.js

Attempting to load enviroment
Starting bot
11/30/2019, 12:11:27 PM :2: Disconnected
11/30/2019, 12:11:27 PM :3: Unable to login check your login token
(node:4564) UnhandledPromiseRejectionWarning: ReferenceError: e is not defined
    at C:\Users\Administrator\Desktop\fivemserverstatus-master\fivemserverstatus
-master\Discord Bot\bot.js:393:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:4564) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
11/30/2019, 12:11:30 PM :2: Loop still running: false

C:\Users\Administrator\Desktop\fivemserverstatus-master\fivemserverstatus-master
\Discord Bot>

The token ID is correct as I pulled it directly from Discord, not sure why we are receiving this error.

**Comment by draZer0** [comment]
Is this the first time using the bot? Did you set all the enviroment variables?

**Comment by draZer0** [comment]
No response. Reopen if you still didn't manage to fix it.

**Comment by larscrazynl** [comment]
I have the samen error. 
How can you fix it?
