### ISSUE TITLE
Need help to Do this

### ISSUE THREAD

**Issue by BendaRP** [RoqueDEV/fivemserverstatus#5]
Idk how to setup this pls help me it looks so good and helpful I NEED this!
Pls contact me on discord:
@Bendaツ#2657

**Comment by draZer0** [comment]
Have you tried following the readme or git wiki?

**Comment by BendaRP** [comment]
i did, i cant make this work!! pls contact me on discord bendaツ#2657

**Comment by RoqueDEV** [comment]
What issues do you have?

**Comment by BendaRP** [comment]
idk its just not working, can you contact me on disocrd?a
Bendaツ#6969
(yes i changed my tag)
