### ISSUE TITLE
Cannot see the server?

### ISSUE THREAD

**Issue by saulienis** [RoqueDEV/fivemserverstatus#8]
![image](https://user-images.githubusercontent.com/52180748/71706025-5cb97580-2dda-11ea-9dc5-9387ab3a6c9e.png)

Seems to start,just test launching on windows, but doesn't seem to be able to recognize a zap-hosting server

I did install all dependenies with npm i

**Comment by draZer0** [comment]
Doesn't matter if you host your server on zap-hosting. Are you sure you typed the IP to the server correctly in the enviroment variables (URL_SERVER)?
